name: mob
description: A new app
dependencies:
  common:
    path: ../common
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  #
  flutter_localizations:
    sdk: flutter
  built_value:
  firebase_core: ^0.2.5+1
  cloud_firestore: ^0.8.2+3
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  sqflite: ^0.13.0+1
dev_dependencies:
  test: ^1.5.1
  intl:
  intl_translation:

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true